### ISSUE TITLE
files

### ISSUE THREAD

**Issue by Myrmillion** [HE-Arc/NSA#1]
**Project Logo :**
![logo_mob](https://user-images.githubusercontent.com/1577282/96238833-364a7c80-0f9f-11eb-836f-12cafde956b2.png)

**Maquettes :**
![NSA](https://user-images.githubusercontent.com/1577282/96238986-672ab180-0f9f-11eb-9aca-39af55e47c5b.png)
[NSA.zip](https://github.com/HE-Arc/NSA/files/5390548/NSA.zip)

**Modeles :**
![ModeleConceptuel](https://user-images.githubusercontent.com/1577282/96239010-6e51bf80-0f9f-11eb-8c6e-4ee9c1007c29.png)
![ModelePhysique](https://user-images.githubusercontent.com/1577282/96239017-6f82ec80-0f9f-11eb-8d26-1e6e2cd8fe98.png)

**Cahier des charges :**
[NSA_CdC.pdf](https://github.com/HE-Arc/NSA/files/5390417/NSA_CdC.pdf)

**Comment by grunenwald** [comment]
Un pdf avec que du texte attaché à une page de wiki ? vraiment ? why ?

**Comment by greut** [comment]
Student et Association, c'est le même modèle. Je remplacerais le _password_ de l'association, par un moyen de lier une personne (certainement un Student) au rôle d'administration de l'association (relation 1:n ou n:m)
